const books = [
      {
        title: "Harry Potter and the Sorcerer's Stone",
        author: "J.K. Rowling",
        genre: "Fantasy",
        rack: 1,
        shelf: 1,
        quantity: 7,
        publisher: "Bloomsbury",
        year: 1997,
        isbn: 9780747532699,
        language: "English",
        borrow_count: 50,
        image: "https://m.media-amazon.com/images/I/81DI+BAN2SL._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "The Hunger Games",
        author: "Suzanne Collins",
        genre: "Dystopian",
        rack: 2,
        shelf: 3,
        quantity: 5,
        publisher: "Scholastic Press",
        year: 2008,
        isbn: 9780439023528,
        language: "English",
        borrow_count: 45,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpTWSmQr47NZ0ghAQgOl7ZQDkXcxAamrxMIA&s"
      },
      {
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        genre: "Classic",
        rack: 3,
        shelf: 4,
        quantity: 4,
        publisher: "Charles Scribner's Sons",
        year: 1925,
        isbn: 9780743273565,
        language: "English",
        borrow_count: 35,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThI0027VOWj4BFw-_fXBJD3RlnrIcCIKh67A&s"
      },
      {
        title: "Percy Jackson & the Olympians: The Lightning Thief",
        author: "Rick Riordan",
        genre: "Fantasy",
        rack: 2,
        shelf: 1,
        quantity: 6,
        publisher: "Disney Hyperion",
        year: 2005,
        isbn: 9780786856299,
        language: "English",
        borrow_count: 42,
        image: "https://m.media-amazon.com/images/I/91WN6a6F3RL._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "The Fault in Our Stars",
        author: "John Green",
        genre: "Romance",
        rack: 3,
        shelf: 2,
        quantity: 3,
        publisher: "Dutton Books",
        year: 2012,
        isbn: 9780525478812,
        language: "English",
        borrow_count: 30,
        image: "https://m.media-amazon.com/images/I/817tHNcyAgL._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "The Maze Runner",
        author: "James Dashner",
        genre: "Science Fiction",
        rack: 2,
        shelf: 4,
        quantity: 4,
        publisher: "Delacorte Press",
        year: 2009,
        isbn: 9780385737944,
        language: "English",
        borrow_count: 28,
        image: "https://m.media-amazon.com/images/I/71gl2fmAp7L._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "Divergent",
        author: "Veronica Roth",
        genre: "Dystopian",
        rack: 2,
        shelf: 2,
        quantity: 5,
        publisher: "Katherine Tegen Books",
        year: 2011,
        isbn: 9780062024039,
        language: "English",
        borrow_count: 40,
        image: "https://m.media-amazon.com/images/I/91oNu+R7EUL._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "Pride and Prejudice",
        author: "Jane Austen",
        genre: "Classic",
        rack: 4,
        shelf: 1,
        quantity: 3,
        publisher: "T. Egerton, Whitehall",
        year: 1813,
        isbn: 9781593082017,
        language: "English",
        borrow_count: 32,
        image: "https://m.media-amazon.com/images/I/81me+udV63L._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        genre: "Classic",
        rack: 3,
        shelf: 3,
        quantity: 4,
        publisher: "Little, Brown and Company",
        year: 1951,
        isbn: 9780316769480,
        language: "English",
        borrow_count: 38,
        image: "https://m.media-amazon.com/images/I/8125BDk3l9L._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "The Book Thief",
        author: "Markus Zusak",
        genre: "Historical Fiction",
        rack: 1,
        shelf: 4,
        quantity: 4,
        publisher: "Picador",
        year: 2005,
        isbn: 9780375831003,
        language: "English",
        borrow_count: 25,
        image: "https://m.media-amazon.com/images/I/91JGwQlnu7L._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        genre: "Classic",
        rack: 4,
        shelf: 2,
        quantity: 4,
        publisher: "J.B. Lippincott & Co.",
        year: 1960,
        isbn: 9780061120084,
        language: "English",
        borrow_count: 45,
        image: "https://m.media-amazon.com/images/I/81WojUxbbFL._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "1984",
        author: "George Orwell",
        genre: "Dystopian",
        rack: 2,
        shelf: 5,
        quantity: 6,
        publisher: "Secker & Warburg",
        year: 1949,
        isbn: 9780451524935,
        language: "English",
        borrow_count: 55,
        image: "https://m.media-amazon.com/images/I/51lzkvNlTBL._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "Brave New World",
        author: "Aldous Huxley",
        genre: "Science Fiction",
        rack: 3,
        shelf: 1,
        quantity: 5,
        publisher: "Chatto & Windus",
        year: 1932,
        isbn: 9780060850524,
        language: "English",
        borrow_count: 48,
        image: "https://m.media-amazon.com/images/I/91D4YvdC0dL.jpg"
      },
      {
        title: "Moby-Dick",
        author: "Herman Melville",
        genre: "Adventure",
        rack: 5,
        shelf: 1,
        quantity: 3,
        publisher: "Harper & Brothers",
        year: 1851,
        isbn: 9780142437247,
        language: "English",
        borrow_count: 30,
        image: "https://m.media-amazon.com/images/I/81Baf0m5rBL._UF1000,1000_QL80_.jpg"
      },
      {
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        genre: "Fantasy",
        rack: 1,
        shelf: 2,
        quantity: 8,
        publisher: "George Allen & Unwin",
        year: 1937,
        isbn: 9780547928227,
        language: "English",
        borrow_count: 60,
        image: "https://m.media-amazon.com/images/I/91b0C2YNSrL._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "The Alchemist",
        author: "Paulo Coelho",
        genre: "Philosophy",
        rack: 5,
        shelf: 3,
        quantity: 7,
        publisher: "HarperCollins",
        year: 1988,
        isbn: 9780061122415,
        language: "English",
        borrow_count: 52,
        image: "https://m.media-amazon.com/images/I/71aFt4+OTOL._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "The Shining",
        author: "Stephen King",
        genre: "Horror",
        rack: 6,
        shelf: 1,
        quantity: 4,
        publisher: "Doubleday",
        year: 1977,
        isbn: 9780307743657,
        language: "English",
        borrow_count: 40,
        image: "https://m.media-amazon.com/images/I/81s6DUyQCZL._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "A Game of Thrones",
        author: "George R.R. Martin",
        genre: "Fantasy",
        rack: 1,
        shelf: 3,
        quantity: 6,
        publisher: "Bantam Books",
        year: 1996,
        isbn: 9780553103540,
        language: "English",
        borrow_count: 58,
        image: "https://m.media-amazon.com/images/I/71Jzezm8CBL._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "The Road",
        author: "Cormac McCarthy",
        genre: "Post-Apocalyptic",
        rack: 3,
        shelf: 5,
        quantity: 4,
        publisher: "Alfred A. Knopf",
        year: 2006,
        isbn: 9780307387899,
        language: "English",
        borrow_count: 35,
        image: "https://m.media-amazon.com/images/I/51M7XGLQTBL._AC_UF1000,1000_QL80_.jpg"
      },
      {
        title: "The Kite Runner",
        author: "Khaled Hosseini",
        genre: "Historical Fiction",
        rack: 4,
        shelf: 3,
        quantity: 5,
        publisher: "Riverhead Books",
        year: 2003,
        isbn: 9781594631931,
        language: "English",
        borrow_count: 42,
        image: "https://m.media-amazon.com/images/I/81IzbD2IiIL.jpg"
      },
    ];

module.exports=books;
  